- name: python setup
  include_role:
    name: common
    tasks_from: python.yaml
      
- name: app-setapp
  include_role:
    name: common
    tasks_from: app-setup.yaml

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml