- name: disable nodejs current version
  ansible.builtin.command:
    cmd: "dnf module disable nodejs -y"

- name: enable nodejs:20
  ansible.builtin.command:
    cmd: "dnf module enable nodejs:20 -y" 

- name: installing nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present