- name: "copy {{ component }} service to system directory"
  ansible.builtin.template:
    src: "{{ component }}.Service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{ component }}"
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: restarted # even app is not running we can restart